#cloud-config
package_update: true
package_upgrade: true
packages:
  - mariadb-server
  - galera-4
  - rsync
  - mariadb-client
  - jq
  - netcat

runcmd:
  # Ensure disk is formatted (only if unformatted)
  - if [ ! -d "/mnt/db-data" ]; then mkfs.ext4 ${volume_path}; fi

  # Mount the volume to MySQL data directory
  - mkdir -p /mnt/db-data
  - mount ${volume_path} /mnt/db-data
  - chown -R mysql:mysql /mnt/db-data
  - chmod 700 /mnt/db-data

  # Persist the mount across reboots
  - echo "${volume_path} /mnt/db-data ext4 defaults 0 0" >> /etc/fstab

  # Move MySQL data directory
  - systemctl stop mariadb
  - mv /var/lib/mysql /var/lib/mysql.bak
  - ln -s /mnt/db-data /var/lib/mysql
  - chown -R mysql:mysql /var/lib/mysql
  - systemctl start mariadb

  # Configure Galera Cluster
  - echo "[mysqld]" > /etc/mysql/conf.d/galera.cnf
  - echo "bind-address = 0.0.0.0" >> /etc/mysql/conf.d/galera.cnf
  - echo "default-storage-engine = InnoDB" >> /etc/mysql/conf.d/galera.cnf
  - echo "innodb_autoinc_lock_mode = 2" >> /etc/mysql/conf.d/galera.cnf
  - echo "wsrep_on = ON" >> /etc/mysql/conf.d/galera.cnf
  - echo "wsrep_provider = /usr/lib/galera/libgalera_smm.so" >> /etc/mysql/conf.d/galera.cnf
  - echo "wsrep_cluster_address = \"gcomm://${cluster_ips}\"" >> /etc/mysql/conf.d/galera.cnf
  - echo "wsrep_cluster_name = \"GaleraCluster\"" >> /etc/mysql/conf.d/galera.cnf
  - echo "wsrep_node_name = \"${node_name}\"" >> /etc/mysql/conf.d/galera.cnf
  - echo "wsrep_node_address = \"${node_ip}\"" >> /etc/mysql/conf.d/galera.cnf
  - echo "wsrep_sst_method = rsync" >> /etc/mysql/conf.d/galera.cnf
  - echo "wsrep_sst_auth = root:${mariadb_root_pw}" >> /etc/mysql/conf.d/galera.cnf

  # Start the MariaDB service
  - systemctl enable mariadb
  - systemctl start mariadb

  # Initialize Galera Cluster only on the first node
  - if [ "$node_name" == "db-node-1" ]; then galera_new_cluster; fi

  # Setup Log and Temp Cleanup Cron Jobs
  - echo "0 2 * * * root find /var/log -type f -mtime +7 -exec rm -f {} \;" >> /etc/cron.d/log-cleanup
  - echo "0 3 * * * root find /tmp -type f -mtime +1 -exec rm -f {} \;" >> /etc/cron.d/temp-cleanup

  # Optimize MySQL Tables Weekly
  - echo "0 4 * * 0 root mysql -u root -p${mariadb_root_pw} -e 'SELECT CONCAT(\"OPTIMIZE TABLE \", table_schema, \".\", table_name, \";\") FROM information_schema.tables WHERE table_schema NOT IN (\"mysql\", \"information_schema\", \"performance_schema\", \"sys\");' | mysql -u root -p${mariadb_root_pw}" >> /etc/cron.d/mysql-optimize

  # Set Permissions and Restart Cron
  - chmod 644 /etc/cron.d/log-cleanup
  - chmod 644 /etc/cron.d/temp-cleanup
  - chmod 644 /etc/cron.d/mysql-optimize
  - systemctl restart cron
